### ISSUE TITLE
Suggestions, questions, more

### ISSUE THREAD

**Issue by KineticTheory** [certik/terminal#24]
* Since you have a function `color`, does it make sense to also provide a function to remove color from strings?
```c++
#include <regex>
...
inline std::string remove_color(std::string const &colored_string) {
  std::regex color_regex("\033[" "[[:digit:]]+[m]");
  return std::regex_replace(colored_string, color_regex, "");
}
```
* It might be worth moving Taylor Campbell's code to its own header to make it easier to keep the Copyright intact and associated with his code.
* I chose to add `inline` to most of the functions in `terminal.hh` to avoid possible multiple definition (e.g. lib1->terminal.h, lib2-> terminal.h, app1-> {lib1, lib2}).
* In `terminal_base.h`, I had to add `#define _WINSOCKAPI_` just before `#include <windows.h>` to avoid multiple definition collisions with `winsock2.h` that I use in my code.  I don't really understand this, but this work-around seems to do the right thing.
* In `terminal.h`, I needed to make a few changes to avoid warnings:
  * Fix a warning about incorrect length of strings
```diff
-      write("\0338");       // restore current cursor position
+      write("\033" "8"); // restore current cursor position

-    write("\0337");       // save current cursor position
+    write("\033" "7");           // save current cursor position
```
  * I needed to change a lot of `int` to `size_t` to avoid build warnings under MSVC (with option `/W4`).  There were also some character types that needed to be more specific (`char` -> `char32_t`, etc.).  I'll create a patch file or PR for these so you can review them.  Example:
```diff
-  uint32_t codepoint, state = UTF8_ACCEPT;
+  uint32_t codepoint;
+  uint8_t state = UTF8_ACCEPT;
```

**Comment by certik** [comment]
@KineticTheory thanks a lot for these suggestions. Yes, I like all of these, these are great ideas.
