### ISSUE TITLE
B0 define conflicts on Linux with user code

### ISSUE THREAD

**Issue by certik** [certik/terminal#35]
Due to this define:

https://github.com/bminor/glibc/blob/0b262ca4c64cd9042576ddb9969607c0ea1187d7/bits/termios.h#L288

user code can break. To fix it, we should but
```
#undef B0
```
right after including `termios.h`. The same for all the other constants.

Reported by @KineticTheory.

**Comment by certik** [comment]
This seems to be a known problem, e.g.:

http://eigen.tuxfamily.org/bz/show_bug.cgi?id=365

https://www.mit.edu/afs.new/athena/astaff/source/src-8.2/third/tcsh/mi.termios.c

https://github.com/android/ndk/issues/630

https://github.com/linbox-team/fflas-ffpack/issues/57

https://github.com/littlevgl/lvgl/issues/941#issuecomment-472641950

https://gitlab.mech.kuleuven.be/rob-expressiongraphs/luabind/commit/418e4c852dfa027c386153396534ccf079efbfee

Most codes decided to rename `B0` to something else to avoid this collision. But the other solution is to simply undefine such a macro.

I also found this note, which lists the reserved names that programs should not use. `B0` is among them ("names prefixed with `B` followed by a digit):

https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

**Comment by KineticTheory** [comment]
> This seems to be a known problem, e.g.:
> 
> http://eigen.tuxfamily.org/bz/show_bug.cgi?id=365
> 
> https://www.mit.edu/afs.new/athena/astaff/source/src-8.2/third/tcsh/mi.termios.c
> 
> [android/ndk#630](https://github.com/android/ndk/issues/630)
> 
> [linbox-team/fflas-ffpack#57](https://github.com/linbox-team/fflas-ffpack/issues/57)
> 
> [littlevgl/lvgl#941 (comment)](https://github.com/littlevgl/lvgl/issues/941#issuecomment-472641950)
> 
> https://gitlab.mech.kuleuven.be/rob-expressiongraphs/luabind/commit/418e4c852dfa027c386153396534ccf079efbfee
> 
> Most codes decided to rename `B0` to something else to avoid this collision. But the other solution is to simply undefine such a macro.
> 
> I also found this note, which lists the reserved names that programs should not use. `B0` is among them ("names prefixed with `B` followed by a digit):
> 
> https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

Wow!  Thanks for all of the links.  I’ll pass this along.
